### PR TITLE
Add exclusion functionality

### PR DESCRIPTION
**Pull request by deongroenewald**
- Adds `@NoSpan` decorator to exclude custom tracing spans being generated for classes or their methods.
- Adds `excludeControllers` and `excludeProviders` options to exclude certain class or methods from having spans automatically created for them by the `controllers` and `providers` options, e.g. 3rd-party code where `@NoSpan` decorator is not an option.

### CODE REVIEW

**Comment by omeha2** [comment]
Nice!
@wokim could you check and merge this one?

**Comment by adamhancockcg** [comment]
It would be really handy for us to have this merged also. Can you merge please @wokim?

**Comment by adamhancockcg** [comment]
Sorry to chase, but do you think this can be merged @wokim?

**Comment by adamhancockcg** [comment]
Tagging other maintainers @kurtextrem @mrjomp @samuelmartineau @michalb-goflink 

It would be really handy for us to have this merged please :)

**Pull request merged**
