### PR TITLE
feat: supports nestjs v10

### PR DESCRIPTION
**Pull request by wokim**

### CODE REVIEW

**Comment by gitSambhal** [comment]
Hi @wokim 
It is breaking my CI/CD pipeline. I am using Nest v9 but this version expects Nestjs v10.

image


My `package.json` contains

```
    "@nestjs/common": "^9.0.0",
    "nestjs-ddtrace": "^3.0.0",
```

image

**Comment by gitSambhal** [comment]
@wokim  May be you should increase the major version of this package. Currently in npm the package version is `3.0.3` with Nestjs v10 support and `3.0.2` with v9 support. Better to use `4.0.0` instead of `3.0.3`.

**Comment by jkalberer** [comment]
@wokim - plans to release this?

**Comment by gitSambhal** [comment]
@jkalberer 
I think you can use as follows

For Nest v10
```
npm i nestjs-ddtrace@^4.0.0
```

For Nest v9
```
npm i nestjs-ddtrace@^3.0.4
```

**Pull request merged**
